name: CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, labeled]
    branches:
      - main

  schedule:
    - cron: '/5 * * *'

jobs:
  scheduled-job:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Rodando job agendado
        run: echo "✅ Cron executada com sucesso às 19h Brasília."

  check-label:
    if: github.event_name == 'pull_request' && github.event.action == 'labeled'
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar nome da label
        run: |
          echo "🧩 Uma label foi adicionada ao PR"
          echo "🏷️ Nome da label: ${{ github.event.label.name }}"

  build:
    if: github.event_name != 'schedule' 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './server/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./server

      - name: Build project
        run: npm run build
        working-directory: ./server

  test:
    if: github.event_name != 'schedule'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: './server/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./server

      - name: Run tests
        run: npm test
        working-directory: ./server