name: Cron Job

on:
  schedule:
    # Executa todo dia às 22h UTC, que corresponde a 19h em Brasília (UTC-3)
    - cron: "0 22 * * *"

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Rodando job agendado
        run: echo "✅ Cron executada com sucesso às 19h Brasília."
