name: Cron Job

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Rodando job agendado
        run: echo "✅ Cron executada com sucesso às 19h Brasília."