name: Snyk Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  snyk:
    name: Run Snyk tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./server

      - name: Run Snyk for NPM packages
        uses: snyk/actions/node@master
        with:
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk for Docker image
        uses: snyk/actions/docker@master
        with:
          image: nest-api
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
